# Generated by Django 3.2.9 on 2022-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_mechanic_pairmechanic_serviceoffered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='services',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
